# https://hub.docker.com/_/mysql
# test용 db
version: "3"                                    # docker-compose 파일 버전입니다.
services: # 서비스들을 선언합니다.
  database: # 서비스명을 선언합니다.
    container_name: twf_db
    image: mysql:8
    volumes: # {호스트}:{컨테이너}
      - ./db/conf.d:/etc/mysql/conf.d             # MySQL 설정 파일이 있습니다.
    ports: # 외부로 노출시킬 port 입니다.
      - "3306:3306"
    environment: # 환경 변수
      - MYSQL_DATABASE=twf
      - MYSQL_USER=twf
      - MYSQL_PASSWORD=twf123
      - MYSQL_ROOT_PASSWORD=twf123
      - TZ=Asia/Seoul
  server:
    build: #image를 DockerFile 기반으로 사용한다
      context: .    #DockerFile이 있는 디렉토리
      dockerfile: Dockerfile    #기존에 설정해둔 DockerFile을 지정히여 build 된 jar 파일을 container에 올린다.
    restart: always        #컨테이너 재실행
    depends_on: #database service가 실행된 이후에 실행
      - database
    ports:
      - "8080:8080"
